#!/usr/bin/env groovy
def getHost() {
    def remote = [:]
    remote.name = 'appinhouse'
    remote.host = 'pagemaker.shiyou.kingsoft.com'
    remote.allowAnyHosts = true
    remote.user = 'jenkins-ci'
    return remote
}

remote = getHost()

def deployBySSH() {
    def run_command = """cd /srv/appinhouse \
    && docker-compose down \
    && docker-compose pull \
    && docker-compose up -d
    """
    sshCommand remote: remote, command: run_command
}

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15',
            artifactNumToKeepStr: '20'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Deploy') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: 'jenkins.ssh', keyFileVariable: 'identity')]) {
                        remote.identityFile = identity
                        deployBySSH()          
                    }
                }
            }
        }
    }
}
